name: Fetch new data from covidlive
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */2 * * *'
jobs:
  get-new-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install
    - run: node getData.js

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update data